---
title: "Comparison of openWAR to other implementations of WAR"
author: "Ben Baumer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## Cross-check our WAR with bbref

```{r, message=FALSE}
library(openWAR)
library(openWARData)
library(mosaic)
```

```{r}
data(rWAR)
rWAR2012 <- filter(rWAR, yearId == 2012)
```

```{r}
data(idTT)
WAR <- merge(x=rWAR2012, y=idTT, by.x="playerId", by.y="key_bbref")
data(openWAR.2012)
WAR <- merge(x=WAR, y=openWAR.2012, by.x="key_mlbam", by.y="playerId")
```

```{r, fig.width=6, fig.height=6}
panel.compare = function (x, y,...) {
  panel.xyplot(x,y, pch=19, alpha=0.3, ...)
  panel.abline(0,1, col="darkgray")
  panel.text(0, 0, paste("Correlation =", round(cor(x,y, use="complete.obs"), 3)))
}

xyplot(WAR ~ rWAR, data=WAR, type=c("p", "r", "smooth")
       , panel=panel.compare
       , main="Comparison of openWAR vs. rWAR, 2012"
       , ylab = "Wins Above Replacement (openWAR)"
       , xlab="Wins Above Replacement (rWAR)"
       )
```

```{r, fig.width=6}
cor(WAR ~ rWAR, data=WAR)

favstats(~WAR, data=WAR)
favstats(~rWAR, data=WAR)
densityplot(~WAR + rWAR, data=WAR)
```

```{r}
sum(~RAA, data=WAR)
sum(~rRAA, data=WAR)
sum(~WAR, data=WAR)
sum(~rWAR, data=WAR)
```

